QMS/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from apps.account.views import gettemplates
from apps.errors import views as error_views

urlpatterns = [
    url(r'', include('apps.report.urls', namespace='report')),
    # url(r'^question/',include('apps.question_track.urls',namespace='question')),
    url(r'^account/', include('apps.account.urls', namespace='account')),
    url(r'^admin/', admin.site.urls),
    url(r'^templates/(?P<templates>.*)/', gettemplates, name='templates'),
    url(r'^view_403/$', error_views.view_403, name='view_403'),
    url(r'^view_404/$', error_views.view_404, name='view_404'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/account/urls.py
#!/usr/bin/python3
from django.conf.urls import url
from . import views

app_name = 'account'
urlpatterns = [
    url('signin/', views.Signin.as_view(), name='signin'),
    url('logout/$', views.logout_view, name='logout'),
    url('user/$', views.UserView.as_view(), name='user'),
    url('user_edit/(?P<user_id>.*)/', views.user_edit, name='user_edit'),
    url('upload/', views.save_img, name='upload'),
    url('forget/$', views.ForgetView.as_view(), name='forget'),
    url('reset/$', views.ResetView.as_view(), name='reset'),
    url('img_captcha/$', views.img_captcha, name='img_captcha'),
]

apps/report/urls.py
from django.conf.urls import url
from apps.report import views

app_name = 'report'
urlpatterns = [
    url(r'^$',views.Index.as_view(),name='index'),
    url(r'^household_report/',views.test,name='household_report'),
]

front/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}OZTEC | 报表管理系统{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
{% block links %}{% endblock %}
  <!-- Morris chart -->
{#  <link rel="stylesheet" href="{% static 'adminlte/bower_components/morris.js/morris.css' %}">#}
{#  <!-- jvectormap -->#}
{#  <link rel="stylesheet" href="{% static 'adminlte/bower_components/jvectormap/jquery-jvectormap.css' %}">#}
{#  <!-- Date Picker -->#}
{#  <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">#}
{#  <!-- Daterange picker -->#}
{#  <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.css' %}">#}
{#  <!-- bootstrap wysihtml5 - text editor -->#}
{#  <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">#}

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- jQuery 3 -->
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
{#    <script src="{% static 'adminlte/bower_components/jquery-ui/jquery-ui.min.js' %}"></script>#}
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <!-- Bootstrap 3.3.7 -->
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- Morris.js charts -->
{#    <script src="{% static 'adminlte/bower_components/raphael/raphael.min.js' %}"></script>#}
{#    <script src="{% static 'adminlte/bower_components/morris.js/morris.min.js' %}"></script>#}
    <!-- Sparkline -->
{#    <script src="{% static 'adminlte/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js' %}"></script>#}
    <!-- jvectormap -->
{#    <script src="{% static 'adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>#}
{#    <script src="{% static 'adminlte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>#}
{#    <!-- jQuery Knob Chart -->#}
{#    <script src="{% static 'adminlte/bower_components/jquery-knob/dist/jquery.knob.min.js' %}"></script>#}
{#    <!-- daterangepicker -->#}
{#    <script src="{% static 'adminlte/bower_components/moment/min/moment.min.js' %}"></script>#}
{#    <script src="{% static 'adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.js' %}"></script>#}
{#    <!-- datepicker -->#}
{#    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>#}
{#    <!-- Bootstrap WYSIHTML5 -->#}
{#    <script src="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>#}
{#    <!-- Slimscroll -->#}
{#    <script src="{% static 'adminlte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>#}
{#    <!-- FastClick -->#}
{#    <script src="{% static 'adminlte/bower_components/fastclick/lib/fastclick.js' %}"></script>#}
    <!-- AdminLTE App -->
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{#    <script src="{% static 'adminlte/dist/js/pages/dashboard.js' %}"></script>#}
{#    <!-- AdminLTE for demo purposes -->#}
{#    <script src="{% static 'adminlte/dist/js/demo.js' %}"></script>#}
    <script src="{% static 'js/common/csrfajax.js' %}"></script>
    <script src="{% static 'js/common/message.js' %}"></script>
    <script src="{% static 'js/layer/layer.js' %}"></script>
{% block scripts %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="{% url 'report:index' %}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>O</b>ZT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">OZTEC | 管理系统</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
{#     {% static 'adminlte/dist/img/user2-160x160.jpg' %}       #}
              <img src="/media/{{ request.user.image }}" class="user-image" alt="User Image">
              <span class="hidden-xs">{% if request.user %}{{ request.user }}{% endif %}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="/media/{{ request.user.image }}" class="img-circle" alt="User Image">
                <p>
                  {{ request.user.work_position }}
                  <small>{{ request.user.jobs }}</small>
                </p>
              </li>
              <!-- Menu Body -->
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">个人信息</a>
                </div>
                <div class="pull-right">
                  <a href="{% url 'account:logout' %}" class="btn btn-default btn-flat">退出登录</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="/media/{{ request.user.image }}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{% if request.user %}{{ request.user }}{% endif %}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="搜索...">
          <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
          {% block sidebar %}
          {% endblock %}
          <a href="{% url 'report:index' %}"><li class="header">首页</li></a>

        <li class="treeview">
          <a href="#">
            <i class="fa fa-pie-chart"></i> <span>家用报表</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class=""><a href="#"><i class="fa fa-circle-o"></i> 装机报表</a></li>
            <li><a href="#"><i class="fa fa-circle-o"></i> 装机详情</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="{% url 'account:user' %}">
            <i class="fa fa-bar-chart"></i> <span>公共事业群</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
              <li class=""><a href="{% url 'account:user' %}"><i class="fa fa-circle-o"></i> 公共报表</a></li>
              <li><a href="index2.html"><i class="fa fa-circle-o"></i> 用户组</a></li>
              <li class=""><a href="index.html"><i class="fa fa-circle-o"></i> 用户权限</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="{% url 'account:user' %}">
            <i class="fa fa-user"></i> <span>用户管理</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
              <li class=""><a href="{% url 'account:user' %}"><i class="fa fa-circle-o"></i> 用户</a></li>
              <li><a href="index2.html"><i class="fa fa-circle-o"></i> 用户组</a></li>
              <li class=""><a href="index.html"><i class="fa fa-circle-o"></i> 用户权限</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="{% url 'account:user' %}">
            <i class="fa fa-cog"></i> <span>系统设置</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
              <li class=""><a href="{% url 'account:user' %}"><i class="fa fa-circle-o"></i> ...</a></li>
              <li><a href="index2.html"><i class="fa fa-circle-o"></i> ...</a></li>
              <li class=""><a href="index.html"><i class="fa fa-circle-o"></i> ...</a></li>
          </ul>
        </li>

      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {% block content-title %}Home{% endblock %}
{#        <small>Control panel</small>#}
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">{% block content-path %}{% endblock %}</li>
      </ol>
    </section>
{#    <div style="height: 5px;width: 100%;background-color: #3c8dbc;margin-top: 10px;"></div>#}
    <!-- Main content -->
    <section class="content">
        {% block content %}
        {% endblock %}
    </section>

  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.0
    </div>
    <strong>Oztec &copy; 2016-2018 .</strong> 报表管理系统
  </footer>

  <div class="control-sidebar-bg"></div>
</div>

</body>
</html>

front/templates/common/index.html
{% extends 'common/base.html' %}
{% load  static %}
{% block title %}
OZNER | 报表关系系统
{% endblock %}

{% block scripts %}

{% endblock %}

{% block content-title %}
<h1 class="page-header">首页</h1>
{% endblock %}

{% block content %}
    <div class="row">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="http://www.ozner.net/upload/images/20171208/%E6%9C%8D%E5%8A%A12%E6%89%8B%E6%9C%BA1013062.jpg" alt="...">
          <div class="carousel-caption">
            ...
          </div>
        </div>
        <div class="item">
          <img src="http://www.ozner.net/upload/images/20170407/banner276551185778354.jpg" alt="...">
          <div class="carousel-caption">
            ...
          </div>
        </div>

      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
</div>
    <div class="row" style="margin-top: 15px;">
        <div class="col-md-5" style="margin-top: 10px;">
            <p style="font-size: 16px;margin-top: 8px;"><a href="#"><b>浩泽净水在港公布2017年全年业绩，年度收入同比增长68.2%</b></a></p>
            <p class="navbar-text navbar-right text-justify" style="margin-left: 0;margin-top: 20px;">全天候安全饮用水服务解决方案提供商 — 浩泽净水国际控股有限公司（“浩泽”或“本公司”，连同其附属公司统称“本集团”，股份代号：2014.HK）宣布本集团截至2017年12月31日的年度（“年内”）全年业绩......</p>
        </div>
        <div class="col-md-5">
            <nav class="navbar navbar-default" style="background-color: #ecf0f5;">
                <div class="container-fluid">
                        <ul class="nav navbar-nav">
                            <li><a href="#">浩泽新闻 <span class="sr-only">(current)</span></a></li>
                            <li><a href="#">行业动态</a></li>
                            <li><a href="#">大客户聚集</a></li>
                        </ul>
                </div>
            </nav>
            <div class="content" data-num="1" style="margin-top: -20px;height: 130px;">
                <ul class="list-unstyled"  style="margin: 0;padding: 0">
                    <li>
                        <a target="_blank" class="time" href="http://www.ozner.net/page.aspx?node=36&amp;id=639">2018.06.29</a>
                        <a target="_blank" class="con" href="/page.aspx?node=36&amp;id=639">试水公益新模式，浩泽牵手链家共谱校园安全饮水新篇章</a>
                    </li>
                    <li>
                        <a target="_blank" class="time" href="http://www.ozner.net/page.aspx?node=21&amp;id=638">2018.06.29</a>
                        <a target="_blank" class="con" href="http://www.ozner.net/page.aspx?node=21&amp;id=638">乾县人大调研浩泽（陕西）工厂扶贫工作情况</a>
                    </li>
                    <li>
                        <a target="_blank" class="time" href="http://www.ozner.net/page.aspx?node=36&amp;id=637">2018.06.25</a>
                        <a target="_blank" class="con" href="http://www.ozner.net/page.aspx?node=36&amp;id=637">关注校园饮水安全问题 浩泽直饮水走进希望小学</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-2">
            <div class="right fl hidden-xs">
					<h5>【浩泽净水 02014.HK】</h5>
					<h1>
                        HK$
                        <span class="gp-dqjg">1.84</span><img src="" class="gp-dqjg-img"></h1>
					<h5 class="add"><span class="gp-zdz">-0.020</span>&nbsp;&nbsp;&nbsp;(<span class="gp-zdb">-1.075%</span>)</h5>
					<h6 class="enddate">
						截至
						<span class="gp-time">2018/07/06&nbsp;&nbsp;11:05</span>
					</h6>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <ul id="valing">
                <li><img src="http://www.ozner.net/upload/images/20171208/%E7%99%BD38075031.jpg" alt=""></li>
                <li><img src="http://www.ozner.net/upload/images/20170227/hz25850103.jpg" alt=""></li>
                <li><img src="http://www.ozner.net/upload/images/20170406/banner-525-21483813.jpg" alt=""></li>
                <li><img src="http://www.ozner.net/upload/images/20170227/hz41076654.jpg" alt=""></li>
            </ul>
        </div>
    </div>

{% endblock %}

{% block links %}
    <style>
        #valing{
            overflow: hidden;
            list-style: none;
            width: 100%;
        }
        #valing li {
            list-style: none;
            height: 200px;
            width: 25%;
            float: left;
            transition-property: width;
            transition-duration: 0.8s;
        }
        #valing:hover li{
            width: 18%;
        }
        #valing li:hover{
            width: 46%;
        }
    </style>
{% endblock %}

front/templates/common/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>用户登录</title>
<script type="text/javascript" src="{% static 'js/common/jquery-3.1.1.min.js' %}" ></script>
<style>
    body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,
        legend,input,textarea,p,blockquote,th,td{
            margin:0;
            padding:0;
        }
    body{
        {#背景虚化#}
        {#font-family: '微软雅黑';#}
        {#background-size:cover;#}
}
    .backimage{
        float: left;
        height: 620px;
        width: 100%;
        background:url({% static 'images/sunrise2.jpg' %}) no-repeat;
        background-size:120%;
        -webkit-filter: blur(10px);
    }
    .login-form-i{
        position: absolute;
        margin: auto;
        top: 0; left: 0; bottom: 0; right: 0;
        border: 1px solid #000;
        background:#000000;
        border-radius: 5px;
        width:240px;
        height:280px;
        padding:5px;
        filter:alpha(Opacity=60);
        -moz-opacity:0.6;
        opacity: 0.6;
    }
    .login-form{
        position: absolute;
        margin: auto;
        top: 0; left: 0; bottom: 0; right: 0;
        border: 1px solid #000;
        {#background:#000;#}
        border-radius: 5px;
        width:240px;
        height:280px;
        padding:5px;
    }
    .login-logo{
        box-sizing: border-box;
        width: 200px;
        height: 36px;
        background-color: #8e7d6c;
        margin: 20px auto;
        border: 1px solid #8e7d6c;
        border-radius: 5px;
        color:white;
        line-height:36px;
        text-align:center;
        opacity:1;
    }

    .login-form .user-input{
        box-sizing: border-box;
        width: 200px;
        height: 36px;
        background-color: #8e7d6c;
        margin: 20px auto;
        border: 1px solid #8e7d6c;
        border-radius: 5px;
        color:white;
        line-height: 36px;
    }
    .login-form .user-input input{
        width: 150px;
        height: 25px;
        border:none;
        outline:none;
        font-size: 12px;
        background-color: #8e7d6c !important;
        text-indent: 5px;
        color:white !important;
        opacity: 2;
    }
    .login-form .user-input img{
        box-sizing: border-box;
        width: 25px;
        height: 25px;
        float: left;
        margin: 5px 5px;
        /*border-right: 2px solid white;*/

    }
    .login-form .login-in input{
        box-sizing: border-box;
        width: 65px;
        height: 30px;
        border: 1px solid rgba(57, 180, 254, 0.98);
        border-radius: 5px;
        margin-left: 35px;
        margin-top: 20px;
        outline:none;
        cursor: pointer;
        font: normal lighter 12px '微软雅黑';
        letter-spacing:12px;
        line-height: 30px;
        text-indent: 10px;
        color:white;
        background-color: rgba(57, 180, 254, 0.98);
    }
</style>
</head>

<body>
{#背景层#}
<div class="backimage"></div>
{#form透明层#}
<div class="login-form-i"></div>
<div class="login-form">
    <form action="" method="post">
        {% csrf_token %}
        <div class="login-logo">QMS系统登录</div>
        <div class="user-input shadow">
            <img src="{% static 'images/user.png' %}" alt="">
            <input id="username" class="int" type="text" name="username" value="用户名" autocomplete="off">
        </div>
        <div class="user-input shadow">
            <img src="{% static 'images/password2.png' %}" alt="">
            <input id="pwd" name="password" type="password" style="display:none;" class="int"/><input id="tx" name="tx" type="text" value="密码" class="int"/>
{#            <input type="password" name="password" value="" autocomplete="off">#}
        </div>
        <div class="login-in">
            <input type="submit" value="登录" class="shadow">
            <input type="button" value="注册" class="shadow">
        </div>
        <span style="display: inline-block;color:red;margin-top: 10px;margin-left: 40px;">{{ state }}</span>
    </form>
</div>
<script>
    $(document).ready(function(){
        $('.shadow').on({
            mouseover:function(){
                $(this).css({'borderWidth':'1px','borderColor':'skyblue','boxShadow':'0 0 2px 2px deepskyblue'});
            }
        ,
            mouseout:function() {
                $(this).css({'borderWidth':'1px','borderColor':'#8e7d6c','boxShadow':'0 0 0 0 deepskyblue'});
            }
        })
    });

    $(document).ready(function(){
        $('.int').on(
            {
                focus:function()
                {
                    {#alert($(this).attr("name"));#}
                    if ($(this).attr("name")=='username')
                    {
                        if ($(this).val()=='用户名') {
                            $(this).val("");
                        }
                    }
                    else if($(this).attr("name")=='tx')
                    {
                        $(this).val("");
                        $(this).css({'display':'none'});
                        var pwd = document.getElementById("pwd");
                        pwd.style.display = "";
                        pwd.focus();
                    }
                }
                ,
                blur:function()
                {
                   if ($(this).attr("name")=='username')
                    {
                        if ($(this).val()=='')
                        {
                            $(this).val("用户名");
                        }
                    }
                    else if($(this).attr("name")=='password')
                    {
                        {#如果用户没输入密码还原默认样式#}
                        if($(this).val()=='')
                        {
                            var tx = document.getElementById("tx");
                            var pwd = document.getElementById("pwd");
                            tx.value="密码";
                            tx.style.display = "";
                            pwd.style.display = "none";
                        }
                    }
                }
            })
    });
    var oDiv=document.getElementById('div1');
    var oDiv2=oDiv.getElementById('div2');
</script>


</body>
</html>